services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Substitua pela porta necessária
    volumes:
      - .:/app
    environment:
      # Defina variáveis de ambiente necessárias aqui
      - EXAMPLE_ENV_VAR=value