especificar_requisitos_sistema_multi_agents:
    description: >
        Realizar levantamento junto aos stakeholders, identificar necessidades de negócio e definir os requisitos funcionais e não funcionais para o sistema CrewAI.
    expected_output: >
        Documento detalhado de requisitos e um overview do escopo e funcionalidades dos agentes necessários.
    agent: arquiteto_de_sistemas

modelar_arquitetura_multi_agents:
    description: >
        Estruturar o diagrama de arquitetura lógica, detalhar interações entre agentes e tarefas e definir tecnologias e integrações principais.
    expected_output: >
        Documento ou diagrama de arquitetura, lista de responsabilidades e integrações selecionadas.
    agent: arquiteto_de_sistemas

definir_documentar_agentes:
    description: >
        Traduzir especificações em perfis de agentes CrewAI, detalhando suas funções, contextos, limitações e informações para o arquivo agents.yaml.
    expected_output: >
        Arquivo agents.yaml pronto para uso, com cada agente documentado de acordo com o padrão do CrewAI.
    agent: engenheiro_de_ia

elaborar_tasks_e_workflows:
    description: >
        Detalhar todas as tarefas do sistema, associando-as aos agentes responsáveis, definindo entradas, saídas e sequenciamento de execução.
    expected_output: >
        Arquivo tasks.yaml com descrição completa das tasks e mapeamento de responsabilidades.
    agent: engenheiro_de_ia

implementar_crew_py_e_integracoes:
    description: >
        Desenvolver o script principal de execução, integrando arquivos agents.yaml e tasks.yaml à lógica do CrewAI, além de configurar quaisquer integrações externas necessárias.
    expected_output: >
        Arquivo crew.py funcional e pronto para execução do sistema, incluindo scripts de integração quando necessário.
    agent: desenvolvedor_backend

validar_testar_ajustar_sistema:
    description: >
        Construir e executar casos de teste, analisar resultados, identificar pontos de melhoria, corrigir bugs e garantir aderência do sistema aos requisitos especificados.
    expected_output: >
        Relatório de testes realizado, sistema validado (crew.py, agents.yaml, tasks.yaml) e documentação de ajustes implementados.
    agent: engenheiro_de_qa
